# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZDaFB1VYNK65lmsjWkO6ycPWo6achVlj
"""

#Lists (MUTABLE,ORDERED)
#BASIC LIST OPERATION

fruits=["apple",'orange','banana','mango']
print("Oriinal List : ",fruits)
print("First Fruit : ",fruits[0])
print("Last Fruit : ",fruits[-1])

#ADDING ITEMS
fruits.append('grapes')
print("After Append : ",fruits)

#REMOVING ITEMS
fruits.remove('banana')
print("After Remove : ",fruits)

#SLICING
print("first 3 fruits")
fruits[:3]

#LIST WITH NUMBERS
numbers=[5,2,3,9,7]
print('Sum=',sum(numbers))
print('max=',max(numbers))
print('min=',min(numbers))
print('sorted=',sorted(numbers))
print('length=',len(numbers))

#TASK 1: CREATE A LIST OF YOUR FAVORITE MOVIES AND PRINT EACH ONE

movies=['spiderman 1','spiderman 2','spiderman 3','deadpool','Avengers']

for i in movies:
      print(i)
#print('Movie 1 :',movies[0])
#print('Movie 2 :',movies[1])
#print('Movie 3 :',movies[2])
#print('Movie 4 :',movies[3])
#print('Movie 5 :',movies[4])

#TASK 2: GIVEN A LIST OF NUMBERS,FIND THE AVERAGE

grade=[88,92,78,90,85]
avg= sum(grade)/len(grade)
print('Average is :',avg)

#TASK 3
nums=[1,2,2,3,4,4,5]
unique= list(set(nums))
print('without duplicate',unique)

#TASK 4
#CHECK IF A SPECIFIC ITEM EXIST IN A LIST
COLORS=['red','blue','green','violet']
search='blue'
if search in COLORS:
  print(f"{search} is in colors")
else:
  print(f"{search} is not in colors")

#BASIC DICTINARY OPERATIONS
student={
    'name':'Ram',
    'age':24,
    'course':'IPPR',
    'grade':'A'
}
print('student:',student)
print('Name:',student['name'])
print('keys:',student.keys())
print('values:',student.values())

#ADDING/UPDATING
student['city']='Kathmandu'
student['grade']='A+'
print('updated :',student)

#TASK 4:
  #CREATE A DICTIONARY OF 3 PRODUCTS AND THEIR PRICES
product={
    'apple':0.99,
    'Mango':0.59,
    'Orange':0.79
}
  #ADD A NEW PRODUCT
product['grape']=1.99
  #UPDATE PRICE
product['apple']=1.01
  #DISPLAY ON PRODUCT
for products,price in product.items():

  print(f"{products}:${price}")

#Tuples(immutable,ordered)
#create a tuple of days in a week
days=('Monday','Tuesday','wednesday','Thursday','Friday','Saturday','Sunday')
print("Weekend Days:", days[5:7])
print('weekdays:', days[:5])
print('weekend days',days[-2:])
print('week days',days[:-2])